version: "3"
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: flaskia
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@pg.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: src/app.py
      FLASK_RUN_HOST: 0.0.0.0
      DATABASE_URL: postgresql://admin:admin@db:5432/flaskia

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000

volumes:
  db-data:
  pgadmin_data:
